name: Python Packaging and docker build

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  pypi-release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v4
    -
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . 'wavespectra[extra]'
    -
      name: Test wavespectra
      run: |
        pip install pytest
        py.test -s -v tests
    -
      name: Build package
      run: |
        pip install build
        python -m build -s
    -
      name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.8.1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true

  docker-publish:
    runs-on: ubuntu-latest
    needs: pypi-release
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}